### ISSUE TITLE
Typings for module

### ISSUE THREAD

**Issue by DzmitryU** [sindresorhus/array-uniq#8]
I'm going to use your module in application node+typescript.
What about *.d.ts file for 'array-uniq'?
Is it possible to add typings?

**Comment by SamVerschueren** [comment]
Sorry, it's better to publish them to DefinitelyTyped https://github.com/sindresorhus/ama/issues/439

**Comment by sindresorhus** [comment]
I now accept TypeScript definitions if anyone looking is interested in submitting it here.

See: https://github.com/sindresorhus/ama/issues/439#issuecomment-414212229

Please follow this guide: https://github.com/sindresorhus/typescript-definition-style-guide
